v1 = int(input("Digite o primeiro valor:"))
v2 = int(input("Digite o segundo valor:"))
v3 = int(input("Digite o terceiro valor:"))
v4 = int(input("Digite o quarto valor:"))
v5 = int(input("Digite o quinto valor:"))
